[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on  = "k"
run = "plugin arrow --args=-1"

[[mgr.prepend_keymap]]
on  = "j"
run = "plugin arrow --args=1"

[[mgr.prepend_keymap]]
on  = "K"
run = "plugin parent-arrow --args=-1"

[[mgr.prepend_keymap]]
on  = "J"
run = "plugin parent-arrow --args=1"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
