"$schema" = 'https://starship.rs/config-schema.json'

palette = "terafox"
format = """
[î‚¶](surface0)\
$os\
$sudo\
[î‚¶](fg:surface2 bg:surface0)\
$directory\
[î‚´](fg:surface2 bg:surface1)\
$git_branch\
$git_status\
$package\
$rust\
$golang\
$nodejs\
$terraform\
$java\
$python\
$gcloud\
$cmd_duration\
[î‚´](fg:surface1 bg:surface0)\
$direnv\
[î‚´](fg:surface0)\
$line_break$jobs$status$container$character"""
add_newline = true

[character]
success_symbol = " [ó±©](bold green)"
error_symbol = " [ó±©](bold red)"
vimcmd_symbol = " [ó±¥](bold green)"
vimcmd_replace_one_symbol = " [ó±¥](bold purple)"
vimcmd_replace_symbol = " [ó±¥](bold purple)"
vimcmd_visual_symbol = " [ó±¥](bold yellow)"

[os]
format = '[$symbol](bold surface0_text bg:surface0)[ ](bg:surface0)'
disabled = false

[os.symbols]
Windows = 'ó°²'
Arch = 'ó°£‡'
Ubuntu = 'ïŒ›'
Macos = 'ó°€µ'
Fedora = 'ó°®¤' # ó°£›
Debian = "ó°£š"
Redhat = "ó±„›"
Unknown = 'ó° ¥'

[sudo]
symbol = "ğŸ§™"
format ="[$symbol]($style)"
style = 'bg:surface0'
disabled = false

[directory]
truncate_to_repo = true
truncation_length = 4
truncation_symbol = 'â€¦/'
repo_root_style = 'bold fg:repo_fg bg:surface2'
#before_repo_root_style = 'black bold'
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format ="[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"
style = 'fg:surface2_text bg:surface2'
home_symbol = '~' # ï€•
read_only = ' ï€£ '

[git_branch]
symbol = 'ï˜ '
format ="[ $symbol$branch(:$remote_branch)]($style)"
style = 'fg:surface1_text bg:surface1'

[git_commit]
tag_disabled = false

[git_status]
disabled = false
format = '[ $all_status$ahead_behind]($style)'
style = 'fg:surface1_text bg:surface1'
conflicted = 'ï„ ' #'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'îª˜ '
modified = 'ï„ '
staged = '[ï§\($count\)](green bg:surface1)'
renamed = 'Â» '
deleted = 'ï€” '

[package]
symbol = " ï’‡ "
format ="[î‚µ$symbol$version]($style) "
style = 'fg:surface1_text bg:surface1'
disabled = true

[rust]
symbol = " ó±˜— "
format ="[î‚µ$symbol($version)]($style)"
style = 'fg:surface1_text bg:surface1'
disabled = false

[golang]
disabled = false

[nodejs]
symbol = " îœ˜ "
format ="[î‚µ$symbol($version)]($style)"
style = 'fg:surface1_text bg:surface1'
disabled = true

[terraform]
symbol = " ó±¢ "
format ="[î‚µ$symbol$workspace]($style)"
style = 'fg:surface1_text bg:surface1'

[java]
symbol = " îœ¸ "
format = "[î‚µ$symbol($version)]($style)"
style = 'fg:surface1_text bg:surface1'
disabled = false

[python]
symbol =" ó°Œ  "
format ="[î‚µ${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
style = 'fg:surface1_text bg:surface1'
disabled = false

[gcloud]
disabled = true

[cmd_duration]
format = '[â€Šî‚µ ó°”› $duration]($style)'
style = "fg:surface1_text bg:surface1"

[direnv]
disabled = false
format = '[$symbol $loaded $allowed ]($style)'
style = 'bold surface0_text bg:surface0'
symbol = '' # 'ó°Œª'
allowed_msg = 'ï'
not_allowed_msg = 'ïœ'
denied_msg = 'ï‘¨'
loaded_msg = 'ó°„¯'
unloaded_msg = 'ï’ª'

[status]
format = '[$symbol$maybe_int]($style) '
map_symbol = true
disabled = true

# palette tables should be last in the config âš“ï¸
[palettes.terafox]
pink = "#cb7985"
purple= "#ad5c7c"
red = "#e85c51"
yellow = "#fda47f"
green = "#7aa4a1"
blue = "#5a93aa"
surface0_text = "#eaeeee"
surface1_text = "#cbd9d8"
surface2_text = "#152528"
surface0 = "#254147"
surface1 = "#425e5e"
surface2 = "#587b7b"
repo_fg = "#1d3337"

[palettes.dayfox]
pink = "#a440b5"
purple= "#6e33ce"
red = "#a5222f"
yellow = "#AC5402"
green = "#396847"
blue = "#2848a9"
surface1_text = "#302b5d"
surface0_text = "#643f61"
surface2_text = "#f6f2ee"
surface0 = "#e7d2be"
surface1 = "#d3c7bb"
surface2 = "#824d5b"
repo_fg = "#f4ece6"

